### ISSUE TITLE
can't find any valid value for ORIGINS

### ISSUE THREAD

**Issue by krodelabestiole** [itsmejoeeey/docker-decap-cms-standalone#4]
hello, i'm trying to use decap with a local backend using docker compose and traefik.
(i'm not sure yet if feasible...)

unfortunately no matter what value I try for ORIGINS env var I run into this issue :

```
unko-admin  | /app/netlify-cms-github-oauth-provider/login_script.js:5
unko-admin  |   throw new Error('process.env.ORIGIN MUST be comma separated list \
```

Here is the concerned part of my docker-compose.yml :

```
  unko-admin:
    image: itsmejoeeey/docker-decap-cms-standalone:latest
    container_name: unko-admin
    environment:
      - ORIGINS=...
    labels:
      - "traefik.http.routers.unko-admin.rule=Host(`unko-admin.localhost`)"
```

Here are the different values I have tried (trying also different pseudo domains with the traefik label - that wouldn't make any difference yet) :
```
- ORIGINS=localhost
- ORIGINS=unko-admin
- ORIGINS='unko-admin'
- ORIGINS='unko-admin.localhost,*'
- ORIGINS='unko-admin.localhost,*.localhost'
```
and many others
and since I found this line in your Dockerfile `ENV ORIGINS=http://localhost`
I also tried things like:
```
- ORIGINS='http://localhost'
- ORIGINS='http://unko.localhost/,http://*/'
```

no success yet !

**Comment by itsmejoeeey** [comment]
In my own `docker-compose` the following works for me:

```
    cms:
        # headless decap cms service on port 80
        image: itsmejoeeey/docker-decap-cms-standalone:3.0.3
        restart: always
        environment:
            - ORIGINS=abc.example.com
        ...
```

Might need further investigation.
